name: CI/CD Pipeline for Frontend & Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Backend: Install & test
      - name: Install Backend dependencies
        run: |
          cd backend
          npm install
          npm test

      # 4. Frontend: Install & test
      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install

      # 5. Build Backend Docker image
      - name: Build Backend Docker image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/chat-app/backend:latest ./backend

      # 6. Build Frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/chat-app/frontend:latest ./frontend

      # 7. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 8. Push Backend image
      - name: Push Backend Docker image
        run: |
          docker push $DOCKER_HUB_USERNAME/chat-app/backend:latest

      # 9. Push Frontend image
      - name: Push Frontend Docker image
        run: |
          docker push $DOCKER_HUB_USERNAME/chat-app/frontend:latest
